version: "2.2"
services:
  FakeDns:
    container_name: FakeDns
    image: fakedns
    working_dir: /FakeDns/
    command: python3 /fakedns/fakedns.py -c /fakedns/remote.conf
    volumes:
      - ./:/opt/FakeDns
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
      - "953:953/tcp"
  